apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: projekt_engine:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
---
apiVersion: v1
kind: Service
metadata:
  name: engine
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: engine
