apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: projekt_frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: ENGINE_URL
              value: http://engine:8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30000
  selector:
    app: frontend